"""Add conversations and messages tables

Revision ID: 9ec7e7fe64d7
Revises: 9ecb463521a8
Create Date: 2026-09-13 16:13:43.765499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ec7e7fe64d7'
down_revision: Union[str, Sequence[str], None] = '9ecb463521a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('conversation_uuid')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_uuid', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_uuid')
    )
    op.drop_table('pgvector_collection_384_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgvector_collection_384_1',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('pgvector_collection_384_1_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pgvector_collection_384_1_pkey'))
    )
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
