"""add dummy col

Revision ID: d811e3c61cb8
Revises: a47e18225ee8
Create Date: 2026-09-09 14:46:39.387827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd811e3c61cb8'
down_revision: Union[str, Sequence[str], None] = 'a47e18225ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dummy_col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'dummy_col')
    # ### end Alembic commands ###
