services:
   mongodb:
    image: mongo:7-jammy
    
    container_name: mongodb
    
    ports:
      - "${APP_PORT}:27017"
    
    volumes:
      - mongodb_data:/data/db

    networks:
      - backend
    
    restart: always

networks:
  backend:
  
volumes:
  mongodb_data: